apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "carrental.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.environment.SPRING_DATASOURCE_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.backend.jwt.secret | quote }}
