apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "carrental.name" . }}
    release: {{ .Release.Name }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.backend.environment.SPRING_DATASOURCE_URL | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.backend.environment.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.backend.environment.SPRING_JPA_HIBERNATE_DDL_AUTO | quote }}
  SERVER_PORT: {{ .Values.backend.environment.SERVER_PORT | quote }}
